### ISSUE TITLE
Feature Request: attach second Fan

### ISSUE THREAD

**Issue by Simbamani** [SanaaHamel/nevermore-controller#7]
Dear Sanaa Hamel, thank you for this great Project. I am working at the moment on a ventilation System. This System will ensure an proper ventilation in my 3d printer enclosure. The System will have 2nd Fan one for intake an the other for outlet. It will be great if this feature will be available in your next release.

**Comment by SanaaHamel** [comment]
You can split the PWM wire between the two fans. You can't do the same for tachometer, it'll only work for one fan. When/if runtime defined pin assignments get added (which is more plausible now that persisted settings is done), I'll see if I can add an extra optional tachometer pin. Because this is a rather rare (unique?) setup, I'm not going to put in the time for full integration, it'll just report the sum of all the tachometers instead. This'll let you know if either fan fails (the RPM will notably drop).

**Comment by SanaaHamel** [comment]
As of 0.13+ you can specify multiple tacho pins. These are summed, and reported as a single fan.
